# -*- coding: utf-8 -*-
"""ARIMA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r5um3fJmJP9hpF9NlIGCJIyPAT3EXie7
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
from google.colab import files
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller, coint
import matplotlib.pyplot as plt
import warnings
import os
from IPython.display import display, Image

warnings.filterwarnings("ignore")

# Function to clean series (handle NaN/Inf)
def clean_series(series, name):
    try:
        print(f"Checking {name} for NaN/Inf values...")
        if not pd.api.types.is_numeric_dtype(series):
            raise ValueError(f"{name} contains non-numeric values.")
        if series.isna().any() or np.isinf(series).any():
            print(f"{name} contains NaN or Inf values. Cleaning...")
            series = series.fillna(method='ffill').fillna(method='bfill').dropna()
            series = series.replace([np.inf], series.max())
            series = series.replace([-np.inf], series.min())
        if series.isna().any():
            raise ValueError(f"{name} still contains NaN values after cleaning.")
        if len(series) == 0:
            raise ValueError(f"{name} is empty after cleaning.")
        print(f"{name} is clean with {len(series)} observations.")
        return series
    except Exception as e:
        raise ValueError(f"Failed to clean {name}: {str(e)}")

# Upload Excel files for Johnson & Johnson, Tesla, and Universal
print("Please upload JOHNSON AND JOHNSON.xlsx")
jnj_upload = files.upload()
jnj_filename = list(jnj_upload.keys())[0]
jnj_df = pd.read_excel(jnj_filename)

print("Please upload TESLA.xlsx")
tesla_upload = files.upload()
tesla_filename = list(tesla_upload.keys())[0]
tesla_df = pd.read_excel(tesla_filename)

print("Please upload Universal.xlsx")
universal_upload = files.upload()
universal_filename = list(universal_upload.keys())[0]
universal_df = pd.read_excel(universal_filename)

# Print available columns for verification
print("\nJohnson & Johnson columns:", list(jnj_df.columns))
print("Tesla columns:", list(tesla_df.columns))
print("Universal columns:", list(universal_df.columns))

# Verify 'Close' column exists
for df, name in [(jnj_df, "Johnson & Johnson"), (tesla_df, "Tesla"), (universal_df, "Universal")]:
    if 'Close' not in df.columns:
        raise ValueError(f"{name} Excel file must contain a 'Close' column.")

# Extract closing prices
jnj_close = jnj_df['Close']
tesla_close = tesla_df['Close']
universal_close = universal_df['Close']

# Clean series
jnj_close = clean_series(jnj_close, "Johnson & Johnson Close")
tesla_close = clean_series(tesla_close, "Tesla Close")
universal_close = clean_series(universal_close, "Universal Close")

# Ensure datetime index
def ensure_datetime_index(df, series, name):
    try:
        if not pd.api.types.is_datetime64_any_dtype(df.index):
            if 'Local Date' in df.columns:
                df['Local Date'] = pd.to_datetime(df['Local Date'], unit='D', origin='1899-12-30', errors='coerce')
                if df['Local Date'].isna().all():
                    raise ValueError(f"Invalid datetime values in Local Date for {name}.")
                df.set_index('Local Date', inplace=True)
                series.index = df.index
            else:
                print(f"Warning: No datetime column found for {name}. Using default index.")
                df.index = pd.RangeIndex(len(df))
                series.index = df.index
        return df, series
    except Exception as e:
        print(f"Warning: Failed to set datetime index for {name}: {str(e)}. Using default index.")
        df.index = pd.RangeIndex(len(df))
        series.index = df.index
        return df, series

jnj_df, jnj_close = ensure_datetime_index(jnj_df, jnj_close, "Johnson & Johnson Close")
tesla_df, tesla_close = ensure_datetime_index(tesla_df, tesla_close, "Tesla Close")
universal_df, universal_close = ensure_datetime_index(universal_df, universal_close, "Universal Close")

# Ensure all series have the same length
min_length = min(len(jnj_close), len(tesla_close), len(universal_close))
jnj_close = jnj_close[:min_length]
tesla_close = tesla_close[:min_length]
universal_close = universal_close[:min_length]

# Dictionary to store series for easier iteration
series_dict = {
    "Johnson & Johnson": jnj_close,
    "Tesla": tesla_close,
    "Universal": universal_close
}

# Data validation
print("\nData Validation:")
for name, series in series_dict.items():
    print(f"{name}:")
    print(f"  Length: {len(series)}")
    print(f"  NaN count: {series.isna().sum()}")
    print(f"  Infinite values: {np.isinf(series).sum()}")
    print(f"  Variance: {series.var():.4f}")

# Check if min_length is sufficient
if min_length < 50:
    print("Warning: Data length is very short (%d). Cointegration tests may be unreliable." % min_length)

# Random Walk Test
def random_walk_test(series, name):
    print(f"\nRandom Walk Test for {name}:")
    diff = series.diff().dropna()
    if np.var(diff) < 1e-5:
        print(f"{name} resembles a random walk (low variance in differences).")
    else:
        print(f"{name} does not clearly exhibit random walk behavior.")

# Unit Root Test (ADF only)
def unit_root_test(series, name):
    print(f"\nUnit Root Test (ADF) for {name}:")
    try:
        series_clean = clean_series(series.dropna(), name)
        adf_result = adfuller(series_clean)
        print(f'ADF Statistic: {adf_result[0]:.4f}')
        print(f'p-value: {adf_result[1]:.4f}')
        print(f'Critical Values: {adf_result[4]}')
        print("Interpretation:")
        if adf_result[1] < 0.05:
            print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
        else:
            print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")
    except Exception as e:
        print(f"Error in unit root test for {name}: {e}")

# Cointegration Test (Engle-Granger)
def cointegration_test(series1, series2, name1, name2):
    print(f"\nCointegration Test (Engle-Granger) between {name1} and {name2}:")
    try:
        series1_clean = clean_series(series1.dropna(), name1)
        series2_clean = clean_series(series2.dropna(), name2)
        score, p_value, _ = coint(series1_clean, series2_clean)
        print(f'Cointegration test statistic: {score:.4f}')
        print(f'p-value: {p_value:.4f}')
        if p_value < 0.05:
            print(f"Interpretation: {name1} and {name2} are cointegrated.")
        else:
            print(f"Interpretation: {name1} and {name2} are not cointegrated.")
    except Exception as e:
        print(f"Error in cointegration test: {e}")

# Function to find best ARIMA model
def find_best_arima(series, name, max_p=2, max_d=1, max_q=2):
    print(f"Fitting ARIMA for {name}...")
    best_aic = float('inf')
    best_order = None
    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except Exception as e:
                    print(f"  Failed ARIMA({p},{d},{q}) for {name}: {e}")
                    continue
    if best_order is None:
        print(f"Error: No valid ARIMA model found for {name}. Skipping.")
        return None
    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Perform tests and ARIMA modeling for all series
arima_orders = {}
arima_models = {}
print("\nStarting ARIMA modeling...")
for name, series in series_dict.items():
    random_walk_test(series, name)
    unit_root_test(series, name)
    order = find_best_arima(series, name)
    if order is None:
        arima_orders[name] = None
        arima_models[name] = None
        continue
    try:
        model = ARIMA(series, order=order).fit()
        arima_orders[name] = order
        arima_models[name] = model
        print(f"ARIMA model fitted for {name}.")
    except Exception as e:
        print(f"Error fitting final ARIMA model for {name}: {e}")
        arima_orders[name] = order
        arima_models[name] = None

# Forecast next 30 periods
forecast_steps = 30
forecasts = {}
print("\nGenerating forecasts...")
for name, model in arima_models.items():
    if model is None:
        print(f"Skipping forecast for {name} due to model fitting error.")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)
        continue
    try:
        forecasts[name] = model.forecast(steps=forecast_steps)
        print(f"Forecast generated for {name}.")
    except Exception as e:
        print(f"Error generating forecast for {name}: {e}")
        forecasts[name] = pd.Series([np.nan] * forecast_steps)

# Create forecast index
last_index = min_length - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot all series with forecasts
print("\nPlotting combined series with forecasts...")
plt.figure(figsize=(14, 8))
colors = ['blue', 'green', 'purple']
i = 0
for name, series in series_dict.items():
    plt.plot(series, label=f'{name} Historical', color=colors[i], alpha=0.5)
    plt.plot(forecast_index, forecasts[name], label=f'{name} Forecast', color=colors[i], linestyle='--')
    i += 1
plt.title('Johnson & Johnson, Tesla, Universal Closing Prices with Forecasts')
plt.legend()
plt.savefig('combined_forecast.png')
plt.show()
plt.close()
display(Image('combined_forecast.png'))

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    print(f"\nPlotting forecast for {name}...")
    if model is None:
        print(f"Skipping plot for {name} due to model fitting error.")
        return
    try:
        forecast_obj = model.get_forecast(steps=steps)
        forecast = forecast_obj.predicted_mean
        conf_int = forecast_obj.conf_int()
        forecast_index = range(len(series), len(series) + steps)
        plt.figure(figsize=(12, 6))
        plt.plot(series, label=f'{name} Historical')
        plt.plot(forecast_index, forecast, label='Forecast', color='red')
        plt.fill_between(forecast_index,
                         conf_int.iloc[:, 0],
                         conf_int.iloc[:, 1],
                         color='pink',
                         alpha=0.3,
                         label='95% Confidence Interval')
        plt.title(f'{name} Price Forecast')
        plt.legend()
        plt.savefig(f'{name}_forecast.png')
        plt.show()
        plt.close()
        display(Image(f'{name}_forecast.png'))
        # Forecast interpretation
        last_value = series.iloc[-1]
        mean_forecast = forecast.mean()
        print(f"\nForecast Interpretation for {name}:")
        print(f"Last observed value: {last_value:.2f}")
        print(f"Average forecast value: {mean_forecast:.2f}")
        print(f"Forecast change: {mean_forecast - last_value:.2f}")
        if mean_forecast > last_value:
            print("Trend: Upward forecast trend")
        elif mean_forecast < last_value:
            print("Trend: Downward forecast trend")
        else:
            print("Trend: Flat forecast trend")
        print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")
    except Exception as e:
        print(f"Error plotting forecast for {name}: {e}")

# Generate detailed forecast plots and interpretations
for name, model in arima_models.items():
    plot_forecast(model, series_dict[name], name)

# Perform pairwise cointegration tests
pairs = [
    ("Johnson & Johnson", "Tesla", jnj_close, tesla_close),
    ("Johnson & Johnson", "Universal", jnj_close, universal_close),
    ("Tesla", "Universal", tesla_close, universal_close)
]

print("\nCointegration Tests:")
for name1, name2, series1, series2 in pairs:
    cointegration_test(series1, series2, name1, name2)

# Print forecast values for next 5 periods
print("\nForecast Values for Next 5 Periods:")
for name, forecast in forecasts.items():
    print(f"\n{name} Forecast Values (next 5 periods):")
    print(forecast[:5])

# List and download saved plots
print("\nSaved Plots:")
saved_files = [f for f in os.listdir() if f.endswith('.png')]
for f in saved_files:
    print(f"- {f}")
    files.download(f)
if not saved_files:
    print("No plots were saved.")