# -*- coding: utf-8 -*-
"""Copy of Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJzc2bPvDAZWcykvSoA6-Bc_iYygYoJm
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.arima.model as arima
from google.colab import auth
from googleapiclient.discovery import build
from google.colab import drive

# Authenticate Google Drive access
drive.mount('/content/drive')

# Define the path to the uploaded Excel files in Google Drive
apple_file_path = "/content/drive/My Drive/APPLE 1 MIN.xlsx"
microsoft_file_path = "/content/drive/My Drive/MICROSOFT 1 MIN.xlsx"

# Load data
apple_df = pd.read_excel(apple_file_path)
microsoft_df = pd.read_excel(microsoft_file_path)

# Extract closing prices
apple_close = apple_df['Close']
microsoft_close = microsoft_df['Close']

# Perform unit root tests (ADF test)
def adf_test(series, title):
    result = ts.adfuller(series)
    print(f"\n{title} ADF Test:")
    print(f"ADF Statistic: {result[0]}")
    print(f"p-value: {result[1]}")
    print("Critical Values:", result[4])

adf_test(apple_close, "Apple Close Prices")
adf_test(microsoft_close, "Microsoft Close Prices")

# Check for cointegration
coint_test = ts.coint(apple_close, microsoft_close)
print("\nCointegration Test:")
print(f"T-Statistic: {coint_test[0]}")
print(f"p-value: {coint_test[1]}")

# Fit ARMA model
def fit_arma(series, order):
    model = arima.ARIMA(series, order=order)
    fitted_model = model.fit()
    print(f"\nARMA{order} Model Summary:")
    print(fitted_model.summary())

fit_arma(apple_close, (1,0,1))
fit_arma(microsoft_close, (1,0,1))

!jupyter nbconvert --execute --to html "/content/Untitled5.ipynb"

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.arima.model as arima
import os

# Verify uploaded files exist
assert os.path.exists("/content/APPLE 1 MIN.xlsx"), "Apple file not found!"
assert os.path.exists("/content/MICROSOFT 1 MIN.xlsx"), "Microsoft file not found!"

# Load data
apple_df = pd.read_excel("/content/APPLE 1 MIN.xlsx")
microsoft_df = pd.read_excel("/content/MICROSOFT 1 MIN.xlsx")

# Extract closing prices
apple_close = apple_df['Close']
microsoft_close = microsoft_df['Close']

# Perform unit root tests (ADF test)
def adf_test(series, title):
    result = ts.adfuller(series)
    print(f"\n{title} ADF Test:")
    print(f"ADF Statistic: {result[0]}")
    print(f"p-value: {result[1]}")
    print("Critical Values:", result[4])

adf_test(apple_close, "Apple Close Prices")
adf_test(microsoft_close, "Microsoft Close Prices")

# Check for cointegration
coint_test = ts.coint(apple_close, microsoft_close)
print("\nCointegration Test:")
print(f"T-Statistic: {coint_test[0]}")
print(f"p-value: {coint_test[1]}")

# Fit ARMA model
def fit_arma(series, order):
    model = arima.ARIMA(series, order=order)
    fitted_model = model.fit()
    print(f"\nARMA{order} Model Summary:")
    print(fitted_model.summary())

fit_arma(apple_close, (1,0,1))
fit_arma(microsoft_close, (1,0,1))

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, arma_order_select_ic
from statsmodels.tsa.api import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import os
import warnings

warnings.filterwarnings("ignore")

# Verify uploaded files exist
apple_filename = "/content/APPLE 1 MIN.xlsx"
msft_filename = "/content/MICROSOFT 1 MIN.xlsx"

if not os.path.exists(apple_filename):
    raise FileNotFoundError(f"Error: '{apple_filename}' not found. Upload manually in the file explorer.")

if not os.path.exists(msft_filename):
    raise FileNotFoundError(f"Error: '{msft_filename}' not found. Upload manually in the file explorer.")

# Load data
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Extract closing prices
try:
    apple_close = apple_df['Close']
    msft_close = msft_df['Close']
except KeyError as e:
    print("Error: 'Close' column not found.")
    print("Apple columns:", apple_df.columns.tolist())
    print("Microsoft columns:", msft_df.columns.tolist())
    raise e

# Align series lengths
min_length = min(len(apple_close), len(msft_close))
apple_close = apple_close[:min_length]
msft_close = msft_close[:min_length]

# ADF unit root test
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f'\nADF Test for {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print('Stationary' if result[1] < 0.05 else 'Non-stationary')
    return result[1] < 0.05

apple_stationary = adf_test(apple_close, 'Apple Close')
msft_stationary = adf_test(msft_close, 'Microsoft Close')

# Difference series if non-stationary
apple_series = apple_close if apple_stationary else apple_close.diff().dropna()
msft_series = msft_close if msft_stationary else msft_close.diff().dropna()

# Fit ARMA models
def fit_arma(series, name):
    try:
        order_selection = arma_order_select_ic(series, ic='bic', trend='c')
        p, q = order_selection.bic_min_order
        print(f'\nOptimal ARMA order for {name}: AR({p}), MA({q})')
        model = ARIMA(series, order=(p, 0, q))
        results = model.fit()
        print(f'{name} ARMA({p},{q}) Summary:')
        print(results.summary())
    except Exception as e:
        print(f'Error fitting ARMA for {name}: {e}')

fit_arma(apple_series, 'Apple')
fit_arma(msft_series, 'Microsoft')

# Johansen cointegration test
def johansen_coint_test(series1, series2):
    data = pd.DataFrame({'Apple': series1, 'Microsoft': series2}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print('\nJohansen Cointegration Test Results:')
    print('Trace Statistic:', result.lr1)
    print('Critical Values (90%, 95%, 99%):')
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f'Cointegration found at rank {i} (95% confidence)')
        else:
            print(f'No cointegration at rank {i} (95% confidence)')

johansen_coint_test(apple_close, msft_close)

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, arma_order_select_ic
from statsmodels.tsa.api import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import warnings
from google.colab import widgets
from google.colab import files

warnings.filterwarnings("ignore")

# Crear un botón de carga
print("Sube tus archivos (APPLE 1 MIN.xlsx y MICROSOFT 1 MIN.xlsx)")
uploaded = files.upload()

# Verificar nombres de archivos
apple_filename = "APPLE 1 MIN.xlsx"
msft_filename = "MICROSOFT 1 MIN.xlsx"

if apple_filename not in uploaded or msft_filename not in uploaded:
    raise FileNotFoundError(f"Error: Asegúrate de subir '{apple_filename}' y '{msft_filename}'.")

# Cargar datos
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Extraer la columna 'Close'
try:
    apple_close = apple_df['Close']
    msft_close = msft_df['Close']
except KeyError as e:
    print("Error: No se encontró la columna 'Close'.")
    print("Apple columnas:", apple_df.columns.tolist())
    print("Microsoft columnas:", msft_df.columns.tolist())
    raise e

# ADF Test para verificar estacionariedad
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f"\nPrueba ADF para {name}:")
    print(f"Estadístico ADF: {result[0]:.4f}")
    print(f"p-valor: {result[1]:.4f}")
    print("Estacionaria" if result[1] < 0.05 else "No estacionaria")
    return result[1] < 0.05

apple_stationary = adf_test(apple_close, "Apple Close")
msft_stationary = adf_test(msft_close, "Microsoft Close")

# Diferenciar serie si no es estacionaria
apple_series = apple_close if apple_stationary else apple_close.diff().dropna()
msft_series = msft_close if msft_stationary else msft_close.diff().dropna()

# Selección automática de orden ARMA y ajuste del modelo
def fit_arma(series, name):
    try:
        order_selection = arma_order_select_ic(series, ic='bic', trend='c')
        p, q = order_selection.bic_min_order
        print(f"\nOrden óptimo de ARMA para {name}: AR({p}), MA({q})")
        model = ARIMA(series, order=(p, 0, q))
        results = model.fit()
        print(f"\nResumen de ARMA({p},{q}) para {name}:")
        print(results.summary())
    except Exception as e:
        print(f"Error al ajustar ARMA para {name}: {e}")

fit_arma(apple_series, "Apple")
fit_arma(msft_series, "Microsoft")

# Prueba de cointegración de Johansen
def johansen_coint_test(series1, series2):
    data = pd.DataFrame({"Apple": series1, "Microsoft": series2}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\nResultados de la prueba de cointegración de Johansen:")
    print("Estadístico de traza:", result.lr1)
    print("Valores críticos (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f"Se encontró cointegración en el rango {i} (95% de confianza)")
        else:
            print(f"No hay cointegración en el rango {i} (95% de confianza)")

johansen_coint_test(apple_close, msft_close)

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, arma_order_select_ic
from statsmodels.tsa.api import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import warnings
import os
from google.colab import files
import ipywidgets as widgets

warnings.filterwarnings("ignore")

# Botón de carga con ipywidgets
upload_button = widgets.FileUpload(accept='.xlsx', multiple=True)

print("Haz clic en el botón de abajo para subir los archivos (APPLE 1 MIN.xlsx y MICROSOFT 1 MIN.xlsx)")
display(upload_button)

# Esperar a que se suban los archivos antes de procesarlos
while not upload_button.value:
    pass

# Guardar archivos en disco
for filename in upload_button.value.keys():
    with open(filename, 'wb') as f:
        f.write(upload_button.value[filename]['content'])

# Verificar nombres de archivos
apple_filename = "APPLE 1 MIN.xlsx"
msft_filename = "MICROSOFT 1 MIN.xlsx"

if not os.path.exists(apple_filename) or not os.path.exists(msft_filename):
    raise FileNotFoundError(f"Error: Asegúrate de subir '{apple_filename}' y '{msft_filename}'.")

# Cargar datos
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Extraer la columna 'Close'
try:
    apple_close = apple_df['Close']
    msft_close = msft_df['Close']
except KeyError as e:
    print("Error: No se encontró la columna 'Close'.")
    print("Apple columnas:", apple_df.columns.tolist())
    print("Microsoft columnas:", msft_df.columns.tolist())
    raise e

# ADF Test para verificar estacionariedad
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f"\nPrueba ADF para {name}:")
    print(f"Estadístico ADF: {result[0]:.4f}")
    print(f"p-valor: {result[1]:.4f}")
    print("Estacionaria" if result[1] < 0.05 else "No estacionaria")
    return result[1] < 0.05

apple_stationary = adf_test(apple_close, "Apple Close")
msft_stationary = adf_test(msft_close, "Microsoft Close")

# Diferenciar serie si no es estacionaria
apple_series = apple_close if apple_stationary else apple_close.diff().dropna()
msft_series = msft_close if msft_stationary else msft_close.diff().dropna()

# Selección automática de orden ARMA y ajuste del modelo
def fit_arma(series, name):
    try:
        order_selection = arma_order_select_ic(series, ic='bic', trend='c')
        p, q = order_selection.bic_min_order
        print(f"\nOrden óptimo de ARMA para {name}: AR({p}), MA({q})")
        model = ARIMA(series, order=(p, 0, q))
        results = model.fit()
        print(f"\nResumen de ARMA({p},{q}) para {name}:")
        print(results.summary())
    except Exception as e:
        print(f"Error al ajustar ARMA para {name}: {e}")

fit_arma(apple_series, "Apple")
fit_arma(msft_series, "Microsoft")

# Prueba de cointegración de Johansen
def johansen_coint_test(series1, series2):
    data = pd.DataFrame({"Apple": series1, "Microsoft": series2}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\nResultados de la prueba de cointegración de Johansen:")
    print("Estadístico de traza:", result.lr1)
    print("Valores críticos (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f"Se encontró cointegración en el rango {i} (95% de confianza)")
        else:
            print(f"No hay cointegración en el rango {i} (95% de confianza)")

johansen_coint_test(apple_close, msft_close)

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, arma_order_select_ic
from statsmodels.tsa.api import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import os
from google.colab import files
import ipywidgets as widgets

# Crear botones de carga separados
apple_button = widgets.FileUpload(accept='.xlsx', multiple=False)
msft_button = widgets.FileUpload(accept='.xlsx', multiple=False)

print("Sube el archivo 'APPLE 1 MIN.xlsx':")
display(apple_button)

print("\nSube el archivo 'MICROSOFT 1 MIN.xlsx':")
display(msft_button)

# Esperar a que se suban los archivos antes de procesarlos
while not apple_button.value or not msft_button.value:
    pass

# Guardar archivos en disco
for filename in apple_button.value.keys():
    with open(filename, 'wb') as f:
        f.write(apple_button.value[filename]['content'])
apple_filename = list(apple_button.value.keys())[0]

for filename in msft_button.value.keys():
    with open(filename, 'wb') as f:
        f.write(msft_button.value[filename]['content'])
msft_filename = list(msft_button.value.keys())[0]

# Cargar datos
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Extraer columna 'Close'
try:
    apple_close = apple_df['Close']
    msft_close = msft_df['Close']
except KeyError as e:
    print("Error: No se encontró la columna 'Close'.")
    print("Apple columnas:", apple_df.columns.tolist())
    print("Microsoft columnas:", msft_df.columns.tolist())
    raise e

# Prueba de raíz unitaria (ADF)
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f'\nPrueba ADF para {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print('Estacionaria' if result[1] < 0.05 else 'No estacionaria')
    return result[1] < 0.05

apple_stationary = adf_test(apple_close, "Apple Close")
msft_stationary = adf_test(msft_close, "Microsoft Close")

# Diferenciar serie si no es estacionaria
apple_series = apple_close if apple_stationary else apple_close.diff().dropna()
msft_series = msft_close if msft_stationary else msft_close.diff().dropna()

# Ajustar modelos ARMA
def fit_arma(series, name):
    try:
        order_selection = arma_order_select_ic(series, ic='bic', trend='c')
        p, q = order_selection.bic_min_order
        print(f'\nOrden óptimo de ARMA para {name}: AR({p}), MA({q})')
        model = ARIMA(series, order=(p, 0, q))
        results = model.fit()
        print(f'{name} ARMA({p},{q}) Summary:')
        print(results.summary())
    except Exception as e:
        print(f'Error ajustando ARMA para {name}: {e}')

fit_arma(apple_series, "Apple")
fit_arma(msft_series, "Microsoft")

# Prueba de cointegración de Johansen
def johansen_coint_test(series1, series2):
    data = pd.DataFrame({"Apple": series1, "Microsoft": series2}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\nResultados de la prueba de cointegración de Johansen:")
    print("Estadístico de traza:", result.lr1)
    print("Valores críticos (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f"Se encontró cointegración en el rango {i} (95% de confianza)")
        else:
            print(f"No hay cointegración en el rango {i} (95% de confianza)")

johansen_coint_test(apple_close, msft_close)

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, arma_order_select_ic
from statsmodels.tsa.api import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
from google.colab import files

# Subir archivos manualmente
print("Sube el archivo 'APPLE 1 MIN.xlsx':")
apple_uploaded = files.upload()

print("\nSube el archivo 'MICROSOFT 1 MIN.xlsx':")
msft_uploaded = files.upload()

# Obtener nombres de archivos
apple_filename = list(apple_uploaded.keys())[0]
msft_filename = list(msft_uploaded.keys())[0]

# Cargar datos
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Extraer columna 'Close'
try:
    apple_close = apple_df['Close']
    msft_close = msft_df['Close']
except KeyError as e:
    print("Error: No se encontró la columna 'Close'.")
    print("Apple columnas:", apple_df.columns.tolist())
    print("Microsoft columnas:", msft_df.columns.tolist())
    raise e

# Prueba de raíz unitaria (ADF)
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f'\nPrueba ADF para {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print('Estacionaria' if result[1] < 0.05 else 'No estacionaria')
    return result[1] < 0.05

apple_stationary = adf_test(apple_close, "Apple Close")
msft_stationary = adf_test(msft_close, "Microsoft Close")

# Diferenciar serie si no es estacionaria
apple_series = apple_close if apple_stationary else apple_close.diff().dropna()
msft_series = msft_close if msft_stationary else msft_close.diff().dropna()

# Ajustar modelos ARMA
def fit_arma(series, name):
    try:
        order_selection = arma_order_select_ic(series, ic='bic', trend='c')
        p, q = order_selection.bic_min_order
        print(f'\nOrden óptimo de ARMA para {name}: AR({p}), MA({q})')
        model = ARIMA(series, order=(p, 0, q))
        results = model.fit()
        print(f'{name} ARMA({p},{q}) Summary:')
        print(results.summary())
    except Exception as e:
        print(f'Error ajustando ARMA para {name}: {e}')

fit_arma(apple_series, "Apple")
fit_arma(msft_series, "Microsoft")

# Prueba de cointegración de Johansen
def johansen_coint_test(series1, series2):
    data = pd.DataFrame({"Apple": series1, "Microsoft": series2}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\nResultados de la prueba de cointegración de Johansen:")
    print("Estadístico de traza:", result.lr1)
    print("Valores críticos (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f"Se encontró cointegración en el rango {i} (95% de confianza)")
        else:
            print(f"No hay cointegración en el rango {i} (95% de confianza)")

johansen_coint_test(apple_close, msft_close)

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, arma_order_select_ic
from statsmodels.tsa.api import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import os
import ipywidgets as widgets
from IPython.display import display

# Crear botón para seleccionar Apple
apple_dropdown = widgets.Dropdown(
    options=os.listdir('/content'),
    description="Apple File:",
    layout=widgets.Layout(width='50%')
)
display(apple_dropdown)

# Crear botón para seleccionar Microsoft
msft_dropdown = widgets.Dropdown(
    options=os.listdir('/content'),
    description="Microsoft File:",
    layout=widgets.Layout(width='50%')
)
display(msft_dropdown)

# Cargar archivos seleccionados
apple_filename = f"/content/{apple_dropdown.value}"
msft_filename = f"/content/{msft_dropdown.value}"

# Verificar que los archivos existen
if not os.path.exists(apple_filename) or not os.path.exists(msft_filename):
    raise FileNotFoundError(f"Error: Asegúrate de haber subido los archivos antes de seleccionarlos.")

# Cargar datos
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Extraer columna 'Close'
try:
    apple_close = apple_df['Close']
    msft_close = msft_df['Close']
except KeyError as e:
    print("Error: No se encontró la columna 'Close'.")
    print("Apple columnas:", apple_df.columns.tolist())
    print("Microsoft columnas:", msft_df.columns.tolist())
    raise e

# Prueba de raíz unitaria (ADF)
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f'\nPrueba ADF para {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print('Estacionaria' if result[1] < 0.05 else 'No estacionaria')
    return result[1] < 0.05

apple_stationary = adf_test(apple_close, "Apple Close")
msft_stationary = adf_test(msft_close, "Microsoft Close")

# Diferenciar serie si no es estacionaria
apple_series = apple_close if apple_stationary else apple_close.diff().dropna()
msft_series = msft_close if msft_stationary else msft_close.diff().dropna()

# Ajustar modelos ARMA
def fit_arma(series, name):
    try:
        order_selection = arma_order_select_ic(series, ic='bic', trend='c')
        p, q = order_selection.bic_min_order
        print(f'\nOrden óptimo de ARMA para {name}: AR({p}), MA({q})')
        model = ARIMA(series, order=(p, 0, q))
        results = model.fit()
        print(f'{name} ARMA({p},{q}) Summary:')
        print(results.summary())
    except Exception as e:
        print(f'Error ajustando ARMA para {name}: {e}')

fit_arma(apple_series, "Apple")
fit_arma(msft_series, "Microsoft")

# Prueba de cointegración de Johansen
def johansen_coint_test(series1, series2):
    data = pd.DataFrame({"Apple": series1, "Microsoft": series2}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\nResultados de la prueba de cointegración de Johansen:")
    print("Estadístico de traza:", result.lr1)
    print("Valores críticos (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f"Se encontró cointegración en el rango {i} (95% de confianza)")
        else:
            print(f"No hay cointegración en el rango {i} (95% de confianza)")

johansen_coint_test(apple_close, msft_close)

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, arma_order_select_ic
from statsmodels.tsa.api import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import os

# Verificar que los archivos estén presentes en el directorio de Colab
apple_filename = "/content/APPLE 1 MIN.xlsx"
msft_filename = "/content/MICROSOFT 1 MIN.xlsx"

if not os.path.exists(apple_filename) or not os.path.exists(msft_filename):
    raise FileNotFoundError("Error: Asegúrate de haber subido los archivos manualmente en Colab antes de ejecutar el script.")

# Cargar datos
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Extraer columna 'Close'
try:
    apple_close = apple_df['Close']
    msft_close = msft_df['Close']
except KeyError as e:
    print("Error: No se encontró la columna 'Close'.")
    print("Apple columnas:", apple_df.columns.tolist())
    print("Microsoft columnas:", msft_df.columns.tolist())
    raise e

# Prueba de raíz unitaria (ADF)
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f'\nPrueba ADF para {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print('Estacionaria' if result[1] < 0.05 else 'No estacionaria')
    return result[1] < 0.05

apple_stationary = adf_test(apple_close, "Apple Close")
msft_stationary = adf_test(msft_close, "Microsoft Close")

# Diferenciar serie si no es estacionaria
apple_series = apple_close if apple_stationary else apple_close.diff().dropna()
msft_series = msft_close if msft_stationary else msft_close.diff().dropna()

# Ajustar modelos ARMA
def fit_arma(series, name):
    try:
        order_selection = arma_order_select_ic(series, ic='bic', trend='c')
        p, q = order_selection.bic_min_order
        print(f'\nOrden óptimo de ARMA para {name}: AR({p}), MA({q})')
        model = ARIMA(series, order=(p, 0, q))
        results = model.fit()
        print(f'{name} ARMA({p},{q}) Summary:')
        print(results.summary())
    except Exception as e:
        print(f'Error ajustando ARMA para {name}: {e}')

fit_arma(apple_series, "Apple")
fit_arma(msft_series, "Microsoft")

# Prueba de cointegración de Johansen
def johansen_coint_test(series1, series2):
    data = pd.DataFrame({"Apple": series1, "Microsoft": series2}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\nResultados de la prueba de cointegración de Johansen:")
    print("Estadístico de traza:", result.lr1)
    print("Valores críticos (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f"Se encontró cointegración en el rango {i} (95% de confianza)")
        else:
            print(f"No hay cointegración en el rango {i} (95% de confianza)")

johansen_coint_test(apple_close, msft_close)

import pandas as pd
import numpy as np
from statsmodels.tsa.stattools import adfuller, arma_order_select_ic
from statsmodels.tsa.api import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import os

# Definir rutas de archivos
apple_filename = "/content/APPLE 1 MIN.xlsx"
msft_filename = "/content/MICROSOFT 1 MIN.xlsx"

# Verificar que los archivos estén presentes en el directorio de Colab
if not os.path.exists(apple_filename) or not os.path.exists(msft_filename):
    raise FileNotFoundError("Error: Asegúrate de haber subido los archivos manualmente en Colab antes de ejecutar el script.")

# Cargar datos
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Extraer columna 'Close'
try:
    apple_close = apple_df['Close']
    msft_close = msft_df['Close']
except KeyError as e:
    print("Error: No se encontró la columna 'Close'.")
    print("Apple columnas:", apple_df.columns.tolist())
    print("Microsoft columnas:", msft_df.columns.tolist())
    raise e

# Prueba de raíz unitaria (ADF)
def adf_test(series, name):
    result = adfuller(series, autolag='AIC')
    print(f'\nPrueba ADF para {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print('Estacionaria' if result[1] < 0.05 else 'No estacionaria')
    return result[1] < 0.05

apple_stationary = adf_test(apple_close, "Apple Close")
msft_stationary = adf_test(msft_close, "Microsoft Close")

# Diferenciar serie si no es estacionaria
apple_series = apple_close if apple_stationary else apple_close.diff().dropna()
msft_series = msft_close if msft_stationary else msft_close.diff().dropna()

# Ajustar modelos ARMA
def fit_arma(series, name):
    try:
        order_selection = arma_order_select_ic(series, ic='bic', trend='c')
        p, q = order_selection.bic_min_order
        print(f'\nOrden óptimo de ARMA para {name}: AR({p}), MA({q})')
        model = ARIMA(series, order=(p, 0, q))
        results = model.fit()
        print(f'{name} ARMA({p},{q}) Summary:')
        print(results.summary())
    except Exception as e:
        print(f'Error ajustando ARMA para {name}: {e}')

fit_arma(apple_series, "Apple")
fit_arma(msft_series, "Microsoft")

# Prueba de cointegración de Johansen
def johansen_coint_test(series1, series2):
    data = pd.DataFrame({"Apple": series1, "Microsoft": series2}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\nResultados de la prueba de cointegración de Johansen:")
    print("Estadístico de traza:", result.lr1)
    print("Valores críticos (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f"Se encontró cointegración en el rango {i} (95% de confianza)")
        else:
            print(f"No hay cointegración en el rango {i} (95% de confianza)")

johansen_coint_test(apple_close, msft_close)

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.arima.model as arima
import os

# Verificar archivos
apple_filename = "/content/APPLE 1 MIN.xlsx"
msft_filename = "/content/MICROSOFT 1 MIN.xlsx"

if not os.path.exists(apple_filename) or not os.path.exists(msft_filename):
    raise FileNotFoundError("Error: Asegúrate de haber subido los archivos manualmente antes de ejecutar el script.")

# Cargar datos
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Extraer columna 'Close'
try:
    apple_close = apple_df['Close']
    msft_close = msft_df['Close']
except KeyError:
    print("Error: No se encontró la columna 'Close'. Revisa los nombres de las columnas.")
    print("Apple columnas:", apple_df.columns.tolist())
    print("Microsoft columnas:", msft_df.columns.tolist())
    raise

# Prueba de raíz unitaria (ADF)
def adf_test(series, name):
    result = ts.adfuller(series)
    print(f'\nPrueba ADF para {name}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print('Estacionaria' if result[1] < 0.05 else 'No estacionaria')

adf_test(apple_close, "Apple Close")
adf_test(msft_close, "Microsoft Close")

# Cointegración
coint_test = ts.coint(apple_close, msft_close)
print("\nPrueba de Cointegración:")
print(f'T-Statistic: {coint_test[0]}')
print(f'p-value: {coint_test[1]}')

# Ajuste de modelos ARMA
def fit_arma(series, name):
    try:
        model = arima.ARIMA(series, order=(1,0,1))
        fitted_model = model.fit()
        print(f'\nModelo ARMA para {name}:')
        print(fitted_model.summary())
    except Exception as e:
        print(f'Error ajustando ARMA para {name}: {e}')

fit_arma(apple_close, "Apple")
fit_arma(msft_close, "Microsoft")

import matplotlib.pyplot as plt
from statsmodels.tsa.vector_ar.vecm import coint_johansen

# 📈 Perform Johansen Cointegration Test
def johansen_test(series1, series2):
    data = pd.concat([series1, series2], axis=1).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\n📊 Johansen Cointegration Test:")
    print("🔹 Trace Statistic:", result.lr1)
    print("🔸 Critical Values (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f'✅ Cointegration found at rank {i} (95% confidence)')
        else:
            print(f'⚠️ No cointegration at rank {i} (95% confidence)')

johansen_test(cost_close, wmt_close)

# Fit Best ARIMA Model
def fit_arima(series, name):
    model = arima.ARIMA(series, order=(1,1,1))  # Adjust parameters if necessary
    results = model.fit()
    print(f'\n⚙️ ARIMA Model Summary for {name}:')
    print(results.summary())
    return results

cost_arima = fit_arima(cost_close, "COST")
wmt_arima = fit_arima(wmt_close, "WMT")

# 📈 Forecast Next Periods
def forecast_arima(model, steps, name):
    forecast = model.get_forecast(steps=steps)
    forecast_df = forecast.conf_int()
    forecast_df["Predicted"] = forecast.predicted_mean
    forecast_df.index = range(len(model.data.endog), len(model.data.endog) + steps)

    # 📉 Plot Forecast
    plt.figure(figsize=(10,5))
    plt.plot(model.data.endog, label="Actual Data", color="blue")
    plt.plot(forecast_df["Predicted"], label="Forecast", color="red")
    plt.fill_between(forecast_df.index, forecast_df.iloc[:,0], forecast_df.iloc[:,1], color="gray", alpha=0.2)
    plt.legend()
    plt.title(f"{name} - ARIMA Forecast ({steps} periods)")
    plt.show()

forecast_arima(cost_arima, 30, "COST")  # Forecasting next 30 periods
forecast_arima(wmt_arima, 30, "WMT")  # Forecasting next 30 periods

# Import required libraries
import pandas as pd
import numpy as np
from google.colab import files
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt

# Upload Excel files
print("Please upload APPLE 1 MIN Excel file")
apple_upload = files.upload()
apple_filename = list(apple_upload.keys())[0]
apple_df = pd.read_excel(apple_filename)

print("Please upload MICROSOFT 1 MIN Excel file")
msft_upload = files.upload()
msft_filename = list(msft_upload.keys())[0]
msft_df = pd.read_excel(msft_filename)

# Print available columns
print("\nAPPLE 1 MIN DataFrame columns:", list(apple_df.columns))
print("MICROSOFT 1 MIN DataFrame columns:", list(msft_df.columns))

# Prompt user for the correct column name
close_column = input("Please enter the column name containing closing prices (case-sensitive): ")

# Check if the specified column exists and extract closing prices
if close_column not in apple_df.columns or close_column not in msft_df.columns:
    print(f"Error: Column '{close_column}' not found in one or both DataFrames")
    print("Please check the column names above and ensure both files have the specified column")
    raise KeyError(f"Column '{close_column}' not found")

apple_close = apple_df[close_column]
msft_close = msft_df[close_column]

# Ensure both series have the same length
min_length = min(len(apple_close), len(msft_close))
apple_close = apple_close[:min_length]
msft_close = msft_close[:min_length]

# Function for unit root tests with interpretation
def unit_root_tests(series, name):
    print(f"\nUnit Root Tests for {name}:")

    # ADF Test
    adf_result = adfuller(series)
    print("ADF Test:")
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")

    # KPSS Test
    kpss_result = kpss(series, regression='c')
    print("\nKPSS Test:")
    print(f'KPSS Statistic: {kpss_result[0]:.4f}')
    print(f'p-value: {kpss_result[1]:.4f}')
    print(f'Critical Values: {kpss_result[3]}')
    print("Interpretation:")
    if kpss_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is non-stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be stationary")

# Perform unit root tests
unit_root_tests(apple_close, "APPLE")
unit_root_tests(msft_close, "MICROSOFT")

# Cointegration test with interpretation
def cointegration_test(df):
    result = coint_johansen(df, det_order=0, k_ar_diff=1)
    print("\nJohansen Cointegration Test:")
    print(f"Trace statistic: {result.lr1}")
    print(f"Critical values (90%, 95%, 99%): {result.cvt}")
    print("Interpretation:")
    for i in range(len(result.lr1)):
        if result.lr1[i] > result.cvt[i, 1]:
            print(f"  - r = {i}: Cointegration exists at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) > 95% critical value ({result.cvt[i, 1]:.2f})")
        else:
            print(f"  - r = {i}: No cointegration at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) <= 95% critical value ({result.cvt[i, 1]:.2f})")
    if result.lr1[0] > result.cvt[0, 1]:
        print("Conclusion: APPLE and MICROSOFT are cointegrated - they share a long-run equilibrium relationship")
    else:
        print("Conclusion: No evidence of cointegration between APPLE and MICROSOFT")

# Prepare data for cointegration
coint_df = pd.DataFrame({
    'APPLE': apple_close,
    'MICROSOFT': msft_close
}).dropna()
cointegration_test(coint_df)

# Function to find best ARIMA model with interpretation
def find_best_arima(series, name, max_p=3, max_d=2, max_q=3):
    best_aic = float('inf')
    best_order = None

    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue

    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Find and fit best ARIMA models
apple_order = find_best_arima(apple_close, "APPLE")
msft_order = find_best_arima(msft_close, "MICROSOFT")

# Fit final ARIMA models
apple_model = ARIMA(apple_close, order=apple_order).fit()
msft_model = ARIMA(msft_close, order=msft_order).fit()

# Forecast next 30 periods (30 minutes for 1-min data)
forecast_steps = 30
apple_forecast = apple_model.forecast(steps=forecast_steps)
msft_forecast = msft_model.forecast(steps=forecast_steps)

# Create forecast index
last_index = len(apple_close) - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot original series with forecasts
plt.figure(figsize=(12,6))
plt.plot(apple_close, label='APPLE Historical')
plt.plot(forecast_index, apple_forecast, label='APPLE Forecast', color='red')
plt.plot(msft_close, label='MICROSOFT Historical')
plt.plot(forecast_index, msft_forecast, label='MICROSOFT Forecast', color='green')
plt.title('APPLE and MICROSOFT Closing Prices with Forecasts (1-Min)')
plt.legend()
plt.show()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()

    forecast_index = range(len(series), len(series) + steps)

    plt.figure(figsize=(12,6))
    plt.plot(series, label=f'{name} Historical')
    plt.plot(forecast_index, forecast, label='Forecast', color='red')
    plt.fill_between(forecast_index,
                    conf_int.iloc[:, 0],
                    conf_int.iloc[:, 1],
                    color='pink',
                    alpha=0.3,
                    label='95% Confidence Interval')
    plt.title(f'{name} Price Forecast (1-Min)')
    plt.legend()
    plt.show()

    # Forecast interpretation
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    print(f"\nForecast Interpretation for {name}:")
    print(f"Last observed value: {last_value:.2f}")
    print(f"Average forecast value: {mean_forecast:.2f}")
    print(f"Forecast change: {mean_forecast - last_value:.2f}")
    if mean_forecast > last_value:
        print("Trend: Upward forecast trend")
    elif mean_forecast < last_value:
        print("Trend: Downward forecast trend")
    else:
        print("Trend: Flat forecast trend")
    print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")

# Generate detailed forecast plots and interpretations
plot_forecast(apple_model, apple_close, "APPLE")
plot_forecast(msft_model, msft_close, "MICROSOFT")

# Print forecast values
print("\nAPPLE Forecast Values (next 5 periods):")
print(apple_forecast[:5])
print("\nMICROSOFT Forecast Values (next 5 periods):")
print(msft_forecast[:5])

# Import required libraries
import pandas as pd
import numpy as np
from google.colab import files
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller, kpss
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt
import os

# Function to upload files with error handling
def upload_file(prompt):
    print(prompt)
    try:
        uploaded = files.upload()
        if not uploaded:
            print("Upload failed. No file selected.")
            return None
        filename = list(uploaded.keys())[0]
        return filename
    except Exception as e:
        print(f"Error during upload: {str(e)}")
        print("Try uploading a smaller file or use Google Drive (instructions below).")
        return None

# Alternative: Mount Google Drive if upload fails
def mount_drive_and_get_file(file_name):
    from google.colab import drive
    print("Mounting Google Drive...")
    drive.mount('/content/drive')
    file_path = f'/content/drive/My Drive/{file_name}'
    if os.path.exists(file_path):
        return file_path
    else:
        print(f"File {file_name} not found in Google Drive root directory.")
        return None

# Upload Excel files
apple_filename = upload_file("Please upload APPLE 1 MIN Excel file")
if not apple_filename:
    print("Attempting to load APPLE 1 MIN.xlsx from Google Drive...")
    apple_filename = mount_drive_and_get_file("APPLE 1 MIN.xlsx")
if not apple_filename:
    raise FileNotFoundError("Could not load APPLE 1 MIN.xlsx. Please check file and try again.")

msft_filename = upload_file("Please upload MICROSOFT 1 MIN Excel file")
if not msft_filename:
    print("Attempting to load MICROSOFT 1 MIN.xlsx from Google Drive...")
    msft_filename = mount_drive_and_get_file("MICROSOFT 1 MIN.xlsx")
if not msft_filename:
    raise FileNotFoundError("Could not load MICROSOFT 1 MIN.xlsx. Please check file and try again.")

# Read Excel files
apple_df = pd.read_excel(apple_filename)
msft_df = pd.read_excel(msft_filename)

# Print available columns
print("\nAPPLE 1 MIN DataFrame columns:", list(apple_df.columns))
print("MICROSOFT 1 MIN DataFrame columns:", list(msft_df.columns))

# Prompt user for the correct column name
close_column = input("Please enter the column name containing closing prices (case-sensitive): ")

# Check if the specified column exists and extract closing prices
if close_column not in apple_df.columns or close_column not in msft_df.columns:
    print(f"Error: Column '{close_column}' not found in one or both DataFrames")
    print("Please check the column names above and ensure both files have the specified column")
    raise KeyError(f"Column '{close_column}' not found")

apple_close = apple_df[close_column]
msft_close = msft_df[close_column]

# Ensure both series have the same length
min_length = min(len(apple_close), len(msft_close))
apple_close = apple_close[:min_length]
msft_close = msft_close[:min_length]

# Function for unit root tests with interpretation
def unit_root_tests(series, name):
    print(f"\nUnit Root Tests for {name}:")

    # ADF Test
    adf_result = adfuller(series)
    print("ADF Test:")
    print(f'ADF Statistic: {adf_result[0]:.4f}')
    print(f'p-value: {adf_result[1]:.4f}')
    print(f'Critical Values: {adf_result[4]}')
    print("Interpretation:")
    if adf_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be non-stationary")

    # KPSS Test
    kpss_result = kpss(series, regression='c')
    print("\nKPSS Test:")
    print(f'KPSS Statistic: {kpss_result[0]:.4f}')
    print(f'p-value: {kpss_result[1]:.4f}')
    print(f'Critical Values: {kpss_result[3]}')
    print("Interpretation:")
    if kpss_result[1] < 0.05:
        print(f"  - p-value < 0.05: Reject null hypothesis - {name} is non-stationary")
    else:
        print(f"  - p-value >= 0.05: Fail to reject null - {name} may be stationary")

# Perform unit root tests
unit_root_tests(apple_close, "APPLE")
unit_root_tests(msft_close, "MICROSOFT")

# Cointegration test with interpretation
def cointegration_test(df):
    result = coint_johansen(df, det_order=0, k_ar_diff=1)
    print("\nJohansen Cointegration Test:")
    print(f"Trace statistic: {result.lr1}")
    print(f"Critical values (90%, 95%, 99%): {result.cvt}")
    print("Interpretation:")
    for i in range(len(result.lr1)):
        if result.lr1[i] > result.cvt[i, 1]:
            print(f"  - r = {i}: Cointegration exists at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) > 95% critical value ({result.cvt[i, 1]:.2f})")
        else:
            print(f"  - r = {i}: No cointegration at 95% confidence level")
            print(f"    Trace statistic ({result.lr1[i]:.2f}) <= 95% critical value ({result.cvt[i, 1]:.2f})")
    if result.lr1[0] > result.cvt[0, 1]:
        print("Conclusion: APPLE and MICROSOFT are cointegrated - they share a long-run equilibrium relationship")
    else:
        print("Conclusion: No evidence of cointegration between APPLE and MICROSOFT")

# Prepare data for cointegration
coint_df = pd.DataFrame({
    'APPLE': apple_close,
    'MICROSOFT': msft_close
}).dropna()
cointegration_test(coint_df)

# Function to find best ARIMA model with interpretation
def find_best_arima(series, name, max_p=3, max_d=2, max_q=3):
    best_aic = float('inf')
    best_order = None

    for p in range(max_p + 1):
        for d in range(max_d + 1):
            for q in range(max_q + 1):
                try:
                    model = ARIMA(series, order=(p, d, q))
                    results = model.fit()
                    if results.aic < best_aic:
                        best_aic = results.aic
                        best_order = (p, d, q)
                except:
                    continue

    print(f"\nBest ARIMA model for {name}:")
    print(f"Order: {best_order}")
    print(f"AIC: {best_aic:.2f}")
    print("Interpretation:")
    print(f"  - p={best_order[0]}: {best_order[0]} autoregressive term(s)")
    print(f"  - d={best_order[1]}: {best_order[1]} difference(s) needed for stationarity")
    print(f"  - q={best_order[2]}: {best_order[2]} moving average term(s)")
    return best_order

# Find and fit best ARIMA models
apple_order = find_best_arima(apple_close, "APPLE")
msft_order = find_best_arima(msft_close, "MICROSOFT")

# Fit final ARIMA models
apple_model = ARIMA(apple_close, order=apple_order).fit()
msft_model = ARIMA(msft_close, order=msft_order).fit()

# Forecast next 30 periods (30 minutes for 1-min data)
forecast_steps = 30
apple_forecast = apple_model.forecast(steps=forecast_steps)
msft_forecast = msft_model.forecast(steps=forecast_steps)

# Create forecast index
last_index = len(apple_close) - 1
forecast_index = range(last_index + 1, last_index + 1 + forecast_steps)

# Plot original series with forecasts
plt.figure(figsize=(12,6))
plt.plot(apple_close, label='APPLE Historical')
plt.plot(forecast_index, apple_forecast, label='APPLE Forecast', color='red')
plt.plot(msft_close, label='MICROSOFT Historical')
plt.plot(forecast_index, msft_forecast, label='MICROSOFT Forecast', color='green')
plt.title('APPLE and MICROSOFT Closing Prices with Forecasts (1-Min)')
plt.legend()
plt.show()

# Detailed forecast plot with confidence intervals and interpretation
def plot_forecast(model, series, name, steps=30):
    forecast_obj = model.get_forecast(steps=steps)
    forecast = forecast_obj.predicted_mean
    conf_int = forecast_obj.conf_int()

    forecast_index = range(len(series), len(series) + steps)

    plt.figure(figsize=(12,6))
    plt.plot(series, label=f'{name} Historical')
    plt.plot(forecast_index, forecast, label='Forecast', color='red')
    plt.fill_between(forecast_index,
                    conf_int.iloc[:, 0],
                    conf_int.iloc[:, 1],
                    color='pink',
                    alpha=0.3,
                    label='95% Confidence Interval')
    plt.title(f'{name} Price Forecast (1-Min)')
    plt.legend()
    plt.show()

    # Forecast interpretation
    last_value = series.iloc[-1]
    mean_forecast = forecast.mean()
    print(f"\nForecast Interpretation for {name}:")
    print(f"Last observed value: {last_value:.2f}")
    print(f"Average forecast value: {mean_forecast:.2f}")
    print(f"Forecast change: {mean_forecast - last_value:.2f}")
    if mean_forecast > last_value:
        print("Trend: Upward forecast trend")
    elif mean_forecast < last_value:
        print("Trend: Downward forecast trend")
    else:
        print("Trend: Flat forecast trend")
    print(f"95% CI range at period {steps}: [{conf_int.iloc[-1, 0]:.2f}, {conf_int.iloc[-1, 1]:.2f}]")

# Generate detailed forecast plots and interpretations
plot_forecast(apple_model, apple_close, "APPLE")
plot_forecast(msft_model, msft_close, "MICROSOFT")

# Print forecast values
print("\nAPPLE Forecast Values (next 5 periods):")
print(apple_forecast[:5])
print("\nMICROSOFT Forecast Values (next 5 periods):")
print(msft_forecast[:5])

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.arima.model as arima
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt
from google.colab import files

# 📂 Upload log DPI dataset manually
print("🔼 Upload the Log DPI dataset (Excel or CSV)")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 📊 Load Data
df = pd.read_excel(filename) if filename.endswith(".xlsx") else pd.read_csv(filename)

# 🔍 Detect Log DPI Column
dpi_column = [col for col in df.columns if "log dpi" in col.lower()]
if dpi_column:
    log_dpi = df[dpi_column[0]]
else:
    print(f"❌ Error: 'Log DPI' column not found in {filename}. Showing available columns:")
    print(df.columns)
    raise KeyError(f"Missing 'Log DPI' column in {filename}")

# 🧹 Clean Data (Remove NaN & Inf)
log_dpi = log_dpi.replace([np.inf, -np.inf], np.nan).dropna()

# 📈 ADF Unit Root Test
def adf_test(series, name):
    result = ts.adfuller(series)
    print(f'\n📊 ADF Test for {name}:')
    print(f'🔹 ADF Statistic: {result[0]:.4f}')
    print(f'📉 p-value: {result[1]:.4f}')
    print('✅ Stationary' if result[1] < 0.05 else '⚠️ Not stationary')

adf_test(log_dpi, "Log DPI")

# 🔗 Johansen Cointegration Test
def johansen_test(series):
    data = pd.DataFrame({'Log DPI': series}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\n📊 Johansen Cointegration Test:")
    print("🔹 Trace Statistic:", result.lr1)
    print("🔸 Critical Values (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f'✅ Cointegration found at rank {i} (95% confidence)')
        else:
            print(f'⚠️ No cointegration at rank {i} (95% confidence)')

johansen_test(log_dpi)

# 📊 Fit ARIMA Model
def fit_arima(series, name):
    model = arima.ARIMA(series, order=(1,1,1))  # Adjust based on stationarity tests
    results = model.fit()
    print(f'\n⚙️ ARIMA Model Summary for {name}:')
    print(results.summary())
    return results

log_dpi_arima = fit_arima(log_dpi, "Log DPI")

# 📈 Forecast Next Periods
def forecast_arima(model, steps, name):
    forecast = model.get_forecast(steps=steps)
    forecast_df = forecast.conf_int()
    forecast_df["Predicted"] = forecast.predicted_mean
    forecast_df.index = range(len(model.data.endog), len(model.data.endog) + steps)

    # 📉 Plot Forecast
    plt.figure(figsize=(10,5))
    plt.plot(model.data.endog, label="Actual Data", color="blue")
    plt.plot(forecast_df["Predicted"], label="Forecast", color="red")
    plt.fill_between(forecast_df.index, forecast_df.iloc[:,0], forecast_df.iloc[:,1], color="gray", alpha=0.2)
    plt.legend()
    plt.title(f"{name} - ARIMA Forecast ({steps} periods)")
    plt.show()

forecast_arima(log_dpi_arima, 30, "Log DPI")  # Forecasting next 30 periods

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.arima.model as arima
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt
from google.colab import files

# 📂 Upload the dataset manually
print("🔼 Upload '21.1.xlsx' dataset")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 📊 Load Data
df = pd.read_excel(filename)

# 🔍 Check available columns
print("📌 Available columns:", df.columns)

# 📈 Extract MONEY (M1 money supply)
money_series = df["MONEY"].replace([np.inf, -np.inf], np.nan).dropna()

# 📊 Visualize the MONEY data
plt.figure(figsize=(10,5))
plt.plot(df["TIME"], money_series, marker="o", linestyle="-", color="blue")
plt.xlabel("Time (Months)")
plt.ylabel("MONEY (M1 Supply)")
plt.title("Time Series of M1 Money Supply")
plt.show()

# 📉 Check for stationarity (ADF Test)
def adf_test(series, name):
    result = ts.adfuller(series)
    print(f'\n📊 ADF Test for {name}:')
    print(f'🔹 ADF Statistic: {result[0]:.4f}')
    print(f'📉 p-value: {result[1]:.4f}')
    print('✅ Stationary' if result[1] < 0.05 else '⚠️ Not stationary')

adf_test(money_series, "MONEY (M1 Supply)")

# 🔗 Johansen Cointegration Test (Self-comparison)
def johansen_test(series):
    data = pd.DataFrame({'MONEY': series}).dropna()
    result = coint_johansen(data, det_order=0, k_ar_diff=1)
    print("\n📊 Johansen Cointegration Test:")
    print("🔹 Trace Statistic:", result.lr1)
    print("🔸 Critical Values (90%, 95%, 99%):")
    print(result.cvt)
    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f'✅ Cointegration found at rank {i} (95% confidence)')
        else:
            print(f'⚠️ No cointegration at rank {i} (95% confidence)')

johansen_test(money_series)

# 📊 Fit ARIMA Model (Adjust Based on ADF Results)
def fit_arima(series, name):
    model = arima.ARIMA(series, order=(1,1,1))  # Adjust based on stationarity tests
    results = model.fit()
    print(f'\n⚙️ ARIMA Model Summary for {name}:')
    print(results.summary())
    return results

money_arima = fit_arima(money_series, "MONEY (M1 Supply)")

# 📈 Forecast Next Periods
def forecast_arima(model, steps, name):
    forecast = model.get_forecast(steps=steps)
    forecast_df = forecast.conf_int()
    forecast_df["Predicted"] = forecast.predicted_mean
    forecast_df.index = range(len(model.data.endog), len(model.data.endog) + steps)

    # 📉 Plot Forecast
    plt.figure(figsize=(10,5))
    plt.plot(model.data.endog, label="Actual Data", color="blue")
    plt.plot(forecast_df["Predicted"], label="Forecast", color="red")
    plt.fill_between(forecast_df.index, forecast_df.iloc[:,0], forecast_df.iloc[:,1], color="gray", alpha=0.2)
    plt.legend()
    plt.title(f"{name} - ARIMA Forecast ({steps} periods)")
    plt.show()

forecast_arima(money_arima, 30, "MONEY (M1 Supply)")  # Forecasting next 30 periods

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.arima.model as arima
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt
from google.colab import files

# 📂 Upload the dataset manually
print("🔼 Upload '21.1.xlsx' dataset")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 📊 Load Data
df = pd.read_excel(filename)

# 🔍 Check available columns
print("📌 Available columns:", df.columns)

# 📈 Extract MONEY (M1 money supply)
money_series = df["MONEY"].replace([np.inf, -np.inf], np.nan).dropna()

# 📊 Visualize the MONEY data
plt.figure(figsize=(10,5))
plt.plot(df["TIME"], money_series, marker="o", linestyle="-", color="blue")
plt.xlabel("Time (Months)")
plt.ylabel("MONEY (M1 Supply)")
plt.title("Time Series of M1 Money Supply")
plt.show()

# 📉 Check for stationarity (ADF Test)
def adf_test(series, name):
    result = ts.adfuller(series)
    print(f'\n📊 ADF Test for {name}:')
    print(f'🔹 ADF Statistic: {result[0]:.4f}')
    print(f'📉 p-value: {result[1]:.4f}')
    print('✅ Stationary' if result[1] < 0.05 else '⚠️ Not stationary')

adf_test(money_series, "MONEY (M1 Supply)")

# 🔗 Johansen Cointegration Test (Fixed 2D Input Issue)
def johansen_test(series):
    # Convert to proper 2D format for Johansen test
    data = pd.DataFrame({'MONEY_1': series, 'MONEY_2': series}).dropna()

    result = coint_johansen(data, det_order=0, k_ar_diff=1)

    print("\n📊 Johansen Cointegration Test:")
    print("🔹 Trace Statistic:", result.lr1)
    print("🔸 Critical Values (90%, 95%, 99%):")
    print(result.cvt)

    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f'✅ Cointegration found at rank {i} (95% confidence)')
        else:
            print(f'⚠️ No cointegration at rank {i} (95% confidence)')

johansen_test(money_series)

# 📊 Fit ARIMA Model (Adjust Based on ADF Results)
def fit_arima(series, name):
    model = arima.ARIMA(series, order=(1,1,1))  # Adjust based on stationarity tests
    results = model.fit()
    print(f'\n⚙️ ARIMA Model Summary for {name}:')
    print(results.summary())
    return results

money_arima = fit_arima(money_series, "MONEY (M1 Supply)")

# 📈 Forecast Next Periods
def forecast_arima(model, steps, name):
    forecast = model.get_forecast(steps=steps)
    forecast_df = forecast.conf_int()
    forecast_df["Predicted"] = forecast.predicted_mean
    forecast_df.index = range(len(model.data.endog), len(model.data.endog) + steps)

    # 📉 Plot Forecast
    plt.figure(figsize=(10,5))
    plt.plot(model.data.endog, label="Actual Data", color="blue")
    plt.plot(forecast_df["Predicted"], label="Forecast", color="red")
    plt.fill_between(forecast_df.index, forecast_df.iloc[:,0], forecast_df.iloc[:,1], color="gray", alpha=0.2)
    plt.legend()
    plt.title(f"{name} - ARIMA Forecast ({steps} periods)")
    plt.show()

forecast_arima(money_arima, 30, "MONEY (M1 Supply)")  # Forecasting next 30 periods

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.arima.model as arima
from statsmodels.tsa.vector_ar.vecm import coint_johansen
import matplotlib.pyplot as plt
from google.colab import files

# 📂 Upload the dataset manually
print("🔼 Upload '21.1.xlsx' dataset")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 📊 Load Data
df = pd.read_excel(filename)

# 🔍 Check available columns
print("📌 Available columns:", df.columns)

# 📈 Extract MONEY (M1 money supply)
money_series = df["MONEY"].replace([np.inf, -np.inf], np.nan).dropna()

# 📊 Visualize the MONEY data
plt.figure(figsize=(10,5))
plt.plot(df["TIME"], money_series, marker="o", linestyle="-", color="blue")
plt.xlabel("Time (Months)")
plt.ylabel("MONEY (M1 Supply)")
plt.title("Time Series of M1 Money Supply")
plt.show()

# 📉 Check for stationarity (ADF Test)
def adf_test(series, name):
    result = ts.adfuller(series)
    print(f'\n📊 ADF Test for {name}:')
    print(f'🔹 ADF Statistic: {result[0]:.4f}')
    print(f'📉 p-value: {result[1]:.4f}')
    print('✅ Stationary' if result[1] < 0.05 else '⚠️ Not stationary')

adf_test(money_series, "MONEY (M1 Supply)")

# 🔗 Fixed Johansen Cointegration Test (Using TIME as secondary series)
def johansen_test(series1, series2):
    data = pd.concat([series1, series2], axis=1).dropna()
    data.columns = ["Series1", "Series2"]  # Ensuring proper naming

    if data.var().min() == 0:
        print("❌ Error: One of the series has zero variance, causing singular matrix.")
        return

    result = coint_johansen(data, det_order=0, k_ar_diff=1)

    print("\n📊 Johansen Cointegration Test:")
    print("🔹 Trace Statistic:", result.lr1)
    print("🔸 Critical Values (90%, 95%, 99%):")
    print(result.cvt)

    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f'✅ Cointegration found at rank {i} (95% confidence)')
        else:
            print(f'⚠️ No cointegration at rank {i} (95% confidence)')

# Using TIME as a secondary variable to prevent singular matrix error
johansen_test(money_series, df["TIME"])

# 📊 Fit ARIMA Model (Adjust Based on ADF Results)
def fit_arima(series, name):
    model = arima.ARIMA(series, order=(1,1,1))  # Adjust based on stationarity tests
    results = model.fit()
    print(f'\n⚙️ ARIMA Model Summary for {name}:')
    print(results.summary())
    return results

money_arima = fit_arima(money_series, "MONEY (M1 Supply)")

# 📈 Forecast Next Periods
def forecast_arima(model, steps, name):
    forecast = model.get_forecast(steps=steps)
    forecast_df = forecast.conf_int()
    forecast_df["Predicted"] = forecast.predicted_mean
    forecast_df.index = range(len(model.data.endog), len(model.data.endog) + steps)

    # 📉 Plot Forecast
    plt.figure(figsize=(10,5))
    plt.plot(model.data.endog, label="Actual Data", color="blue")
    plt.plot(forecast_df["Predicted"], label="Forecast", color="red")
    plt.fill_between(forecast_df.index, forecast_df.iloc[:,0], forecast_df.iloc[:,1], color="gray", alpha=0.2)
    plt.legend()
    plt.title(f"{name} - ARIMA Forecast ({steps} periods)")
    plt.show()

forecast_arima(money_arima, 30, "MONEY (M1 Supply)")  # Forecasting next 30 periods