# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DDS_fRSuq0vpAxZIt8YnOrzSDXgVuRi7
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.vector_ar.vecm as vecm
import matplotlib.pyplot as plt
from google.colab import files

# 📂 Upload the dataset manually
print("🔼 Upload 'Table 22.7' dataset (Excel or CSV)")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 📊 Load Data
df = pd.read_excel(filename) if filename.endswith(".xlsx") else pd.read_csv(filename)

# 🔍 Verify column names
print("📌 Available columns:", df.columns)

# 📈 Extract Treasury Bill Rates
try:
    tb3m = df["TB3M"].replace([np.inf, -np.inf], np.nan).dropna()
    tb6m = df["TB6M"].replace([np.inf, -np.inf], np.nan).dropna()
except KeyError:
    print("❌ Error: Columns 'TB3M' or 'TB6M' not found. Check dataset column names.")
    raise

# 📉 Plot the Two Time Series
plt.figure(figsize=(10,5))
plt.plot(df.index, tb3m, label="TB3M (3-Month Rate)", color="blue")
plt.plot(df.index, tb6m, label="TB6M (6-Month Rate)", color="red")
plt.xlabel("Time (Months)")
plt.ylabel("Treasury Bill Rates")
plt.title("TB3M & TB6M Treasury Bill Rates Over Time")
plt.legend()
plt.show()

# 📊 Unit Root Test (ADF Test)
def adf_test(series, name):
    result = ts.adfuller(series)
    print(f'\n📊 ADF Test for {name}:')
    print(f'🔹 ADF Statistic: {result[0]:.4f}')
    print(f'📉 p-value: {result[1]:.4f}')
    print('✅ Stationary' if result[1] < 0.05 else '⚠️ Not stationary')

adf_test(tb3m, "TB3M (3-Month Rate)")
adf_test(tb6m, "TB6M (6-Month Rate)")

# 🔗 Johansen Cointegration Test
def johansen_test(series1, series2):
    data = pd.concat([series1, series2], axis=1).dropna()
    data.columns = ["TB3M", "TB6M"]

    if data.var().min() == 0:
        print("❌ Error: One series has zero variance, causing singular matrix.")
        return

    result = vecm.coint_johansen(data, det_order=0, k_ar_diff=1)

    print("\n📊 Johansen Cointegration Test:")
    print("🔹 Trace Statistic:", result.lr1)
    print("🔸 Critical Values (90%, 95%, 99%):")
    print(result.cvt)

    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f'✅ Cointegration found at rank {i} (95% confidence)')
        else:
            print(f'⚠️ No cointegration at rank {i} (95% confidence)')

johansen_test(tb3m, tb6m)

# 📌 Model Choice: VAR or First Differences?
if ts.adfuller(tb3m)[1] > 0.05 or ts.adfuller(tb6m)[1] > 0.05:
    print("\n⚠️ Both series have unit roots ➡️ Use first differences in VAR model.")
else:
    print("\n✅ Series are stationary ➡️ VAR model can be estimated in levels.")

import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.tsa.stattools as ts
import statsmodels.tsa.vector_ar.vecm as vecm
import statsmodels.tsa.arima.model as arima
import matplotlib.pyplot as plt
from google.colab import files

# 📂 Upload the dataset manually
print("🔼 Upload 'Table 22.7 (1).txt' dataset")
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# 📊 Load Data as Raw Text and Parse
with open(filename, "r") as file:
    lines = file.readlines()

# 📝 Manually Parse TXT Data
data = []
for line in lines[5:]:  # Skip header lines
    parts = line.split()  # Split by spaces
    if len(parts) >= 3:
        data.append(parts[:3])  # Keep first 3 columns: Date, GS3M, GS6M

# 📊 Convert to DataFrame
df = pd.DataFrame(data, columns=["Date", "GS3M", "GS6M"])
df["GS3M"] = pd.to_numeric(df["GS3M"], errors="coerce")
df["GS6M"] = pd.to_numeric(df["GS6M"], errors="coerce")
df.dropna(inplace=True)  # Remove bad rows

# ✅ Check structure
print("\n📌 Sample data preview:")
print(df.head())

# 📈 Plot TB3M & TB6M Time Series
plt.figure(figsize=(10,5))
plt.plot(df["Date"], df["GS3M"], label="TB3M (3-Month Rate)", color="blue")
plt.plot(df["Date"], df["GS6M"], label="TB6M (6-Month Rate)", color="red")
plt.xlabel("Time (Months)")
plt.ylabel("Treasury Bill Rates")
plt.title("TB3M & TB6M Treasury Bill Rates Over Time")
plt.xticks(rotation=45)  # Improve readability
plt.legend()
plt.show()

# 📊 Unit Root Test (ADF Test)
def adf_test(series, name):
    result = ts.adfuller(series)
    print(f'\n📊 ADF Test for {name}:')
    print(f'🔹 ADF Statistic: {result[0]:.4f}')
    print(f'📉 p-value: {result[1]:.4f}')
    print('✅ Stationary' if result[1] < 0.05 else '⚠️ Not stationary')

adf_test(df["GS3M"], "TB3M (3-Month Rate)")
adf_test(df["GS6M"], "TB6M (6-Month Rate)")

# 🔗 Johansen Cointegration Test
def johansen_test(series1, series2):
    data = pd.concat([series1, series2], axis=1).dropna()
    data.columns = ["TB3M", "TB6M"]

    if data.var().min() == 0:
        print("❌ Error: One series has zero variance, causing singular matrix.")
        return

    result = vecm.coint_johansen(data, det_order=0, k_ar_diff=1)

    print("\n📊 Johansen Cointegration Test:")
    print("🔹 Trace Statistic:", result.lr1)
    print("🔸 Critical Values (90%, 95%, 99%):")
    print(result.cvt)

    for i, stat in enumerate(result.lr1):
        if stat > result.cvt[i, 1]:
            print(f'✅ Cointegration found at rank {i} (95% confidence)')
        else:
            print(f'⚠️ No cointegration at rank {i} (95% confidence)')

johansen_test(df["GS3M"], df["GS6M"])

# 📌 Model Choice: VAR or First Differences?
if ts.adfuller(df["GS3M"])[1] > 0.05 or ts.adfuller(df["GS6M"])[1] > 0.05:
    print("\n⚠️ Both series have unit roots ➡️ Use first differences in VAR model.")
else:
    print("\n✅ Series are stationary ➡️ VAR model can be estimated in levels.")

# 📊 Fit ARIMA Model
def fit_arima(series, name):
    model = arima.ARIMA(series, order=(1,1,1))  # Adjust based on stationarity tests
    results = model.fit()
    print(f'\n⚙️ ARIMA Model Summary for {name}:')
    print(results.summary())
    return results

tb3m_arima = fit_arima(df["GS3M"], "TB3M (3-Month Rate)")
tb6m_arima = fit_arima(df["GS6M"], "TB6M (6-Month Rate)")

# 📈 Forecast Next Periods
def forecast_arima(model, steps, name):
    forecast = model.get_forecast(steps=steps)
    forecast_df = forecast.conf_int()
    forecast_df["Predicted"] = forecast.predicted_mean
    forecast_df.index = range(len(model.data.endog), len(model.data.endog) + steps)

    # 📉 Plot Forecast
    plt.figure(figsize=(10,5))
    plt.plot(model.data.endog, label="Actual Data", color="blue")
    plt.plot(forecast_df["Predicted"], label="Forecast", color="red")
    plt.fill_between(forecast_df.index, forecast_df.iloc[:,0], forecast_df.iloc[:,1], color="gray", alpha=0.2)
    plt.legend()
    plt.title(f"{name} - ARIMA Forecast ({steps} periods)")
    plt.show()

forecast_arima(tb3m_arima, 30, "TB3M (3-Month Rate)")  # Forecasting next 30 periods
forecast_arima(tb6m_arima, 30, "TB6M (6-Month Rate)")  # Forecasting next 30 periods